const state = {
  lang: localStorage.getItem('sahalat_lang')==='en' ? 'en' : 'ar',
  adminAnalyticsEnabled:false,
  loginUsers: [],
  currentUser: null,
  page: 'dashboard',
  accountUser: null,
  selectedLoanId: null,
  selectedPaymentId: null,
  selectedRepaymentRequestId: null,
  paymentActionMode: null,
  capitalTransfers: [],
  capitalHistory: [],
  repaymentRequests: [],
  annualSettlementSummary: null,
  annualSettlementRecords: [],
  annualSettlementYear: new Date().getFullYear(),
  annualSettlementUserId: null,
  settlementTransferTotals: {},
  collectionYears: [],
  expectedInterestByCollectionYear: [],
  selectedCollectionYear: null,
  pendingDeleteTransferId: null,
  pendingEditTransferId: null,
  maxLoan: 50000,
  maxMonths: 36,
  userSharePercent: 40,
  ownerSharePercent: 60,
  systemSettingsId: null,
  users: [],
  authSession: null,
  authUser: null,
  isBootstrapping: true,
  connectionError: '',
  loanRates: null,
  loanSharePolicies: [],
  loans: []
};
